using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SmartSchedulingSystem.Scheduling.Models;

namespace SmartSchedulingSystem.Scheduling.Algorithms.CP
{
    /// <summary>
    /// Represents the course assignment generated by the CP algorithm
    /// </summary>
    public class CourseAssignment
    {
        /// <summary>
        /// Course section information
        /// </summary>
        public CourseSectionInfo Section { get; }
        
        /// <summary>
        /// Assigned teacher
        /// </summary>
        public TeacherInfo Teacher { get; }
        
        /// <summary>
        /// Assigned classroom
        /// </summary>
        public ClassroomInfo Classroom { get; }
        
        /// <summary>
        /// Assigned time slot
        /// </summary>
        public TimeSlotInfo TimeSlot { get; }
        
        /// <summary>
        /// Create a new course assignment
        /// </summary>
        public CourseAssignment(
            CourseSectionInfo section,
            TeacherInfo teacher,
            ClassroomInfo classroom,
            TimeSlotInfo timeSlot)
        {
            Section = section ?? throw new ArgumentNullException(nameof(section));
            Teacher = teacher ?? throw new ArgumentNullException(nameof(teacher));
            Classroom = classroom ?? throw new ArgumentNullException(nameof(classroom));
            TimeSlot = timeSlot ?? throw new ArgumentNullException(nameof(timeSlot));
        }
        
        /// <summary>
        /// Convert to a generic SchedulingAssignment object
        /// </summary>
        public SchedulingAssignment ToSchedulingAssignment(SchedulingProblem problem)
        {
            return new SchedulingAssignment
            {
                SectionId = Section.Id,
                CourseSection = Section,
                TeacherId = Teacher.Id,
                Teacher = Teacher,
                ClassroomId = Classroom.Id,
                Classroom = Classroom,
                TimeSlotId = TimeSlot.Id,
                TimeSlot = TimeSlot
            };
        }
        
        /// <summary>
        /// Return the string representation of the assignment
        /// </summary>
        public override string ToString()
        {
            return $"Course:{Section.CourseName}(ID:{Section.Id}), Teacher:{Teacher.Name}, Classroom:{Classroom.Name}, Time:{TimeSlot.DayName} {TimeSlot.StartTime}";
        }
    }
} 